### ISSUE TITLE
How can VSCode connect to bst-proxy and debug?

### ISSUE THREAD

**Issue by hseirwilliam** [bespoken/alexa-skills-kit-nodejs-lambda-boilerplate#1]
Hi,
I am new with Bespoken and VSCode to make Alexa skill debugging possible.
Here list my outcomes and results using this repository:
1.The "npm run start" gave one public url "https://compassionate-undefined-XXXXXX.bespoken.link" in my local command shell. This url was then listed in the Amazon https Endpoint. When testing,  I can see the JSON messages in the  "Service Response" of Alexa Skill's "Service Simulator". So, everything goes well for now.
2.I then ran the latest VSCODE v1.16 and Debug with "Attach". Please refer to the "launch.json" below for details. However, I can Not get the VSCode to connect to my local "bst-proxy" instance and got the "Cannot connect to runtime process (reason: connect ETIMEDOUT 199.245.58.250:5858)". So, what should I do next to make the VSCode connect to bst-proxy and debug? 
Thanks for anyone's help in advance.
William
=============
launch.json:
{
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "program": "${workspaceRoot}/index.js",
            "port": 5858,
            "address": "compassionate-undefined-XXXXXX.bespoken.link",
            "restart": false,
            "sourceMaps": false,
            "timeout": 600000,
            "localRoot": "${workspaceRoot}",
            "protocol": "legacy",
            "remoteRoot": null
        }

**Comment by jkelvie** [comment]
Hi @hseirwilliam - thanks for using our stuff! I am not expert with vscode, but was just playing around with it a bit. I found that this launch configuration worked:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Proxy",
            "program": "${workspaceRoot}/node_modules/bespoken-tools/bin/bst-proxy.js",
            "args": ["lambda", "src/index.js"],
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

*Make sure to put the relative path to your index.js in the args section*

With that, I was able to add breakpoints to my project and debug it in VSCode. Give it a try and let me know if it works for you.

**Comment by hseirwilliam** [comment]
Your solution works. Thanks.
